version: '3.7'

services:

  lapka_identity:
    image: mobicommunity/lapkaidentity:1.0
    container_name: lapka_identity
    restart: unless-stopped
    ports:
      - 5001:5001
      - 5011:5011
    networks:
      - lapka

  lapka_pets:
    image: mobicommunity/lapkapets:1.0
    container_name: lapka_pets
    restart: unless-stopped
    ports:
      - 5002:5002
      - 5012:5012
    networks:
      - lapka

  lapka_files:
    image: mobicommunity/lapkafiles:1.0
    container_name: lapka_files
    restart: unless-stopped
    ports:
      - 5003:5003
      - 5013:5013
    networks:
      - lapka

  consul:
    image: consul:latest
    container_name: consul
    restart: unless-stopped
    ports:
      - 8500:8500
    networks:
      - lapka

  fabio:
    image: fabiolb/fabio:latest
    container_name: fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    ports:
      - 9998:9998
      - 9999:9999
    networks:
      - lapka

  minio:
    image: minio/minio
    container_name: minio_lapka
    volumes:
      - /minio/data:/data
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=SOMEHARDUSERNAME
      - MINIO_ROOT_PASSWORD=SOMEUNBREAKABLEPASSWORD
    networks:
      - lapka
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/data
    ports:
      - 9200:9200
    networks:
      - lapka

  mongo:
    image: mongo
    container_name: mongo_lapka
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - lapka

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_lapka
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    networks:
      - lapka

  seq:
    image: datalust/seq
    container_name: seq_lapka
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - lapka

networks:
  lapka:
    name: lapka

volumes:
  consul:
    driver: local
  mongo:
    driver: local
  rabbitmq:
    driver: local
  seq:
    driver: local
  elasticsearch:
    driver: local
  minio:
    driver: local